### PR TITLE
Handle HTTP 405 error

### LINKED ISSUE #268: DeleteApplication fails with "Marathon API Error: "
I seem to have this intermittent issue where calling DeleteApplication fails with the error `"Marathon API error: "` and no additional info. Nothing appears in the Marathon logs. 

I'm using Marathon 1.3.0 and Mesos 1.0.1.

Have you encountered this issue at all?

### PR DESCRIPTION
**Pull request by alenkacz**
This fixes #268

### CODE REVIEW

File: error_test.go [hunk 1]
```diff
@@ -61,6 +61,13 @@ func TestErrors(t *testing.T) {
 			errText:  "App '/not_existent' does not exist",
 			content:  `{"message": "App '/not_existent' does not exist"}`,
 		},
+		// 405
+		{
+			httpCode: http.StatusMethodNotAllowed,
+			errCode:  ErrCodeMethodNotAllowed,
+			errText:  "",
+			content:  `{"message": null}`,
```
Comment (timoreimann) [inline error_test.go]: Did you possibly verify that Marathon returns no real content? At least at the time when we created the various error codes, it usually did.

Comment (alenkacz) [reply error_test.go]: yep, that null thing inside json is what marathon returns when you do HTTP DELETE on /v2/apps

Comment (timoreimann) [reply error_test.go]: Gotcha, thanks. 👍
